config/routes.rb
Productively::Application.routes.draw do
  root to: 'static_pages#root'

  resources :users
  resource :session

  namespace :api, defaults: { format: :json } do
    resources :boards, except: [:new, :edit]
    resources :lists, only: [:create, :update, :destroy, :index]
    resources :cards, only: [:create, :update, :destroy, :index]

    # resources :items
    # resources :board_memberships
    # resources :card_assignments
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<!-- <div class="container container-fluid"> -->
  
  <% if signed_in? %>
  <div class="navbar-header">
    <a href="#">
    <button type="button" class="btn btn-default btn-lg">
      <span class="glyphicon glyphicon-th"></span>&nbsp;&nbsp;The Boards
    </button>
    </a>
  </div>
  <% end %>
  
  <div class="navbar-logo">Productively</div>


  <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
    <% if signed_in? %>
        <%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %>
    <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Log In", new_session_url %></li>
      <li><%= link_to "Sign Up", new_user_url %></li>
    </ul>
    <% end %>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>") %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Productively</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/header" %>
  <%= yield %>
</body>
</html>